version: 2
updates:
    # Enable Github Action updates
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "chore(GHA)"
      labels:
          - "dependencies"
          - "patch"
          - "actions"

    # Enable NPM updates
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "chore(Node)"
      labels:
          - "dependencies"
          - "patch"
          - "npm"

    # Enable NPM updates
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "chore(Node)"
      labels:
          - "dependencies"
          - "patch"
          - "npm"